### ISSUE TITLE
Single-quotes are converted to entity values

### ISSUE THREAD

**Issue by jonathankeebler** [TooBug/smsGateway#2]
A call like this
```
gateway.sendMessageToNumber(PHONE_NUMBER, "Don't", DEVICE_ID).then(function()
{
	console.log("Success!");
}).fail(function(message){
	console.log('failed',message);
})
```
will send an SMS with the message:
```
Don&#039;t
```

Not sure if this is an issue with the library or the service itself.

**Comment by TooBug** [comment]
Just looked up my code, nothing done with the content.

I'll confirm later to see where the problem is, maybe restler.js did this, or maybe smsgateway.me.

**Comment by jonathankeebler** [comment]
I tried upgrading restler; didn't make a difference. Can you reproduce too? Emojis are a problem too but that's probably smsgateway.me.

**Comment by TooBug** [comment]
<http://requestb.in/1j8zd681?inspect>

I've tested with request bin, The text content in the post body is not encoded. So it's smsgateway's issue.
